import { ChemicalRecord } from "./types";

export const CHEMICAL_LIBRARY: ChemicalRecord[] = [
  {
    id: "acetone",
    name: "Acetone",
    synonyms: ["Dimethyl ketone"],
    unNa: "UN1090",
    ergGuide: "127",
    idlhPpm: 2500,
    npgPage: "4",
    flags: { oxygenatedVoc: true, flammable: true },
    expected: { pid: "high", fid: "high", ph: "neutral", oxidizerPositive: false, lelBehavior: "strong" },
  },
  {
    id: "toluene",
    name: "Toluene",
    synonyms: ["Methylbenzene"],
    unNa: "UN1294",
    ergGuide: "130",
    idlhPpm: 500,
    npgPage: "334",
    flags: { hydrocarbon: true, flammable: true },
    expected: { pid: "high", fid: "high", ph: "neutral", oxidizerPositive: false, lelBehavior: "strong" },
  },
  {
    id: "mek",
    name: "Methyl Ethyl Ketone (MEK)",
    synonyms: ["2-Butanone"],
    unNa: "UN1193",
    ergGuide: "127",
    idlhPpm: 3000,
    npgPage: "215",
    flags: { oxygenatedVoc: true, flammable: true },
    expected: { pid: "high", fid: "high", ph: "neutral", oxidizerPositive: false, lelBehavior: "strong" },
  },
  {
    id: "ammonia",
    name: "Ammonia",
    synonyms: ["Anhydrous ammonia"],
    unNa: "UN1005",
    ergGuide: "125",
    idlhPpm: 300,
    npgPage: "20",
    flags: { strongBase: true, corrosive: true },
    expected: { pid: "low", fid: "none", ph: "basic", oxidizerPositive: false, lelBehavior: "none" },
  },
  {
    id: "chlorine",
    name: "Chlorine",
    synonyms: ["Cl2"],
    unNa: "UN1017",
    ergGuide: "124",
    idlhPpm: 10,
    npgPage: "74",
    flags: { oxidizer: true, corrosive: true },
    expected: { pid: "none", fid: "none", ph: "acidic", oxidizerPositive: true, lelBehavior: "none" },
  },
  {
    id: "carbon-dioxide",
    name: "Carbon Dioxide",
    synonyms: ["CO2"],
    unNa: "UN1013",
    ergGuide: "120",
    idlhPpm: 40000,
    npgPage: "63",
    flags: { canDisplaceOxygen: true },
    expected: { pid: "none", fid: "none", ph: "acidic", oxidizerPositive: false, lelBehavior: "none" },
  },
  {
    id: "methane",
    name: "Methane",
    synonyms: ["Natural gas"],
    unNa: "UN1971",
    ergGuide: "115",
    idlhPpm: 50000,
    npgPage: "208",
    flags: { hydrocarbon: true, flammable: true, canDisplaceOxygen: true },
    expected: { pid: "none", fid: "high", ph: "neutral", oxidizerPositive: false, lelBehavior: "strong" },
  },
];
